package CetakFilkom.BackEnd;

import java.io.FileNotFoundException;
import java.io.IOException;

import CetakFilkom.*;

/**
 *
 * Class ini pertama kali dijalankan pada aplikasi BackEnd
 */
public class AdminApp extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public AdminApp() {
        initComponents();
        setSize(430, 250);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        try {
            Data.muat();
        } catch (Exception e) {
        }
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        mainPanel = new javax.swing.JPanel();
        buttonPelanggan = new javax.swing.JButton();
        buttonMenu = new javax.swing.JButton();
        buttonPromosi = new javax.swing.JButton();
        buttonPemesanan = new javax.swing.JButton();
        labelAdmin = new javax.swing.JLabel();
        labelPercetakanFilkom = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
                jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));
        jInternalFrame1Layout.setVerticalGroup(
                jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));

        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
                jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));
        jInternalFrame2Layout.setVerticalGroup(
                jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(52, 73, 94));

        buttonPelanggan.setText("Pelanggan ");
        buttonPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPelangganMouseClicked(evt);
            }
        });

        buttonMenu.setText("Menu");
        buttonMenu.setToolTipText("");
        buttonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMenuMouseClicked(evt);
            }
        });

        buttonPromosi.setText("Promosi");
        buttonPromosi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPromosiMouseClicked(evt);
            }
        });

        buttonPemesanan.setText("Pesanan");
        buttonPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    buttonPemesananMouseClicked(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        labelAdmin.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        labelAdmin.setForeground(new java.awt.Color(255, 255, 255));
        labelAdmin.setText("ADMIN");

        labelPercetakanFilkom.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        labelPercetakanFilkom.setForeground(new java.awt.Color(255, 255, 255));
        labelPercetakanFilkom.setText("PERCETAKAN FILKOM");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelPercetakanFilkom, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addComponent(buttonPelanggan)
                                                .addGap(18, 18, 18)
                                                .addComponent(buttonMenu)
                                                .addGap(18, 18, 18)
                                                .addComponent(buttonPromosi)
                                                .addGap(18, 18, 18)
                                                .addComponent(buttonPemesanan)
                                                .addGap(0, 36, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(labelAdmin)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        mainPanelLayout.setVerticalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(labelAdmin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelPercetakanFilkom, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(
                                        mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(buttonPelanggan)
                                                .addComponent(buttonMenu)
                                                .addComponent(buttonPromosi)
                                                .addComponent(buttonPemesanan))
                                .addGap(140, 140, 140)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPelangganMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_buttonPelangganMouseClicked
        // GEN-FIRST:event_buttonPelangganMouseClicked
        PelangganAdmin p = new PelangganAdmin();
        p.setVisible(true);
        dispose();
        // GEN-LAST:event_buttonPelangganMouseClicked
    }// GEN-LAST:event_buttonPelangganMouseClicked

    private void buttonPemesananMouseClicked(java.awt.event.MouseEvent evt) throws FileNotFoundException, IOException {// GEN-FIRST:event_buttonPemesananMouseClicked
        // GEN-FIRST:event_buttonPemesananMouseClicked
        LihatPesanan p = new LihatPesanan();
        p.setVisible(true);
        // GEN-LAST:event_buttonPemesananMouseClicked
    }// GEN-LAST:event_buttonPemesananMouseClicked

    private void buttonPromosiMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_buttonPromosiMouseClicked
        // GEN-FIRST:event_buttonPromosiMouseClicked
        PromosiAdmin p = new PromosiAdmin();
        p.setVisible(true);
        dispose();
        // GEN-LAST:event_buttonPromosiMouseClicked
    }// GEN-LAST:event_buttonPromosiMouseClicked

    private void buttonMenuMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_buttonMenuMouseClicked
        // GEN-FIRST:event_buttonMenuMouseClicked
        MenuAdmin p = new MenuAdmin();
        p.setVisible(true);
        dispose();
        // GEN-LAST:event_buttonMenuMouseClicked
    }// GEN-LAST:event_buttonMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AdminApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonMenu;
    private javax.swing.JButton buttonPelanggan;
    private javax.swing.JButton buttonPemesanan;
    private javax.swing.JButton buttonPromosi;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel labelAdmin;
    private javax.swing.JLabel labelPercetakanFilkom;
    public static javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
