/**
 * Class ini pertama kali dijalankan pada aplikasi FrontEnd
 */
package CetakFilkom.FrontEnd;

import java.io.FileNotFoundException;
import java.io.IOException;

import javax.swing.JOptionPane;

import CetakFilkom.Data;
import CetakFilkom.Order;
import CetakFilkom.Error.DateOutOfBoundsException;

/**
 *
 * @author HP
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public App() {
        try {
            Data.muat();
        } catch (IOException | DateOutOfBoundsException e) {
            e.printStackTrace();
        }
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCustomer = new javax.swing.JLabel();
        jTextFieldNamaCustomer = new javax.swing.JTextField();
        jLabelNamaCustomer = new javax.swing.JLabel();
        lihatMenuButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 335));

        jLabelCustomer.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabelCustomer.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCustomer.setText("PERCETAKAN FILKOM");

        jLabelNamaCustomer.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabelNamaCustomer.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNamaCustomer.setText("ID Pelanggan");

        lihatMenuButton1.setText("Masuk");
        lihatMenuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    lihatMenuButton1ActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(56, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelCustomer)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lihatMenuButton1)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabelNamaCustomer)
                                                        .addGap(49, 49, 49)
                                                        .addComponent(jTextFieldNamaCustomer,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 198,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(56, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldNamaCustomer, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelNamaCustomer))
                                .addGap(51, 51, 51)
                                .addComponent(lihatMenuButton1)
                                .addContainerGap(101, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lihatMenuButton1ActionPerformed(java.awt.event.ActionEvent evt)
            throws FileNotFoundException, IOException {
        String id = (String) jTextFieldNamaCustomer.getText();
        if (!Data.getMapPelanggan().containsKey(id)) {
            JOptionPane.showMessageDialog(this, "Kode / ID Pengguna tidak tersedia", "Error",
                    JOptionPane.ERROR_MESSAGE);
            jTextFieldNamaCustomer.setText("");
            return;
        }

        order = new Order(Data.getMapPelanggan().get(id));
        if (!Data.getMapOrder().containsKey(id)) {
            Data.getMapOrder().put(id, order);
        } else {
            order = Data.getMapOrder().get(id);
        }
        idPelanggan = id;
        MenuCustomer p = new MenuCustomer();
        p.setVisible(true);
        dispose();
    }// GEN-LAST:event_lihatMenuButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    static Order order;
    static String idPelanggan;
    private javax.swing.JLabel jLabelCustomer;
    private javax.swing.JLabel jLabelNamaCustomer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldNamaCustomer;
    private javax.swing.JButton lihatMenuButton1;
    // End of variables declaration//GEN-END:variables
}
