/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CetakFilkom.FrontEnd;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Map;

import javax.swing.SpinnerNumberModel;

import CetakFilkom.Data;
import CetakFilkom.Error.DateOutOfBoundsException;
import CetakFilkom.Error.QuantityException;
import CetakFilkom.Lembaran.*;

/**
 *
 * @author HP
 */
public class MenuCustomer extends javax.swing.JFrame {

        /**
         * Creates new form PelangganGUI
         * 
         * @throws IOException
         * @throws FileNotFoundException
         */
        public MenuCustomer() throws FileNotFoundException, IOException {
                initComponents();
                setLocationRelativeTo(null);
                setResizable(false);
                try (BufferedReader b = new BufferedReader(new FileReader("src\\CetakFilkom\\File\\Menu.txt"))) {
                        String line;
                        while ((line = b.readLine()) != null) {
                                String temp = line.replaceAll(",", " / ");
                                jComboBoxPilihDokumen.addItem(temp);
                        }
                }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                try {
                        Data.muat();
                } catch (IOException | DateOutOfBoundsException e) {
                        e.printStackTrace();
                }

                jPanelHalAkhir = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabelPilihDokumen = new javax.swing.JLabel();
                jComboBoxPilihDokumen = new javax.swing.JComboBox<>();
                addToCartButton = new javax.swing.JButton();
                lihatCartButton = new javax.swing.JButton();
                SpinnerNumberModel model = new SpinnerNumberModel(1, 0, Integer.MAX_VALUE, 1);
                jSpinnerJumlahCopy = new javax.swing.JSpinner(model);
                jLabelJumlahCopy = new javax.swing.JLabel();
                BackButton = new javax.swing.JButton();
                jButtonRemove = new javax.swing.JButton();
                jButtonCartCheckout = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanelHalAkhir.setBackground(new java.awt.Color(52, 73, 94));
                jPanelHalAkhir.setPreferredSize(new java.awt.Dimension(478, 391));

                jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("MENU");

                jLabelPilihDokumen.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
                jLabelPilihDokumen.setForeground(new java.awt.Color(255, 255, 255));
                jLabelPilihDokumen.setText("Pilih Dokumen");
                jLabelPilihDokumen.setToolTipText("");

                addToCartButton.setText("Add To Cart");
                addToCartButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                try {
                                        addToCartButtonActionPerformed(evt);
                                } catch (QuantityException e) {
                                        e.printStackTrace();
                                }
                        }
                });

                lihatCartButton.setText("Lihat Cart");
                lihatCartButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                lihatCartButtonActionPerformed(evt);
                        }
                });

                jLabelJumlahCopy.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
                jLabelJumlahCopy.setForeground(new java.awt.Color(255, 255, 255));
                jLabelJumlahCopy.setText("Jumlah Copy");

                BackButton.setText("Kembali");
                BackButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BackButtonActionPerformed(evt);
                        }
                });

                jButtonRemove.setText("Hapus");
                jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonRemoveActionPerformed(evt);
                        }
                });

                jButtonCartCheckout.setText("Checkout");
                jButtonCartCheckout.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                try {
                                        jButtonCartCheckoutActionPerformed(evt);
                                } catch (IOException e) {
                                        e.printStackTrace();
                                }
                        }
                });

                javax.swing.GroupLayout jPanelHalAkhirLayout = new javax.swing.GroupLayout(jPanelHalAkhir);
                jPanelHalAkhir.setLayout(jPanelHalAkhirLayout);
                jPanelHalAkhirLayout.setHorizontalGroup(
                                jPanelHalAkhirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanelHalAkhirLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanelHalAkhirLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanelHalAkhirLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                .addComponent(BackButton))
                                                                                .addGroup(jPanelHalAkhirLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(29, 29, 29)
                                                                                                .addGroup(jPanelHalAkhirLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(jPanelHalAkhirLayout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(jLabelJumlahCopy)
                                                                                                                                .addGap(49, 49, 49)
                                                                                                                                .addComponent(jSpinnerJumlahCopy,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGroup(jPanelHalAkhirLayout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(jLabelPilihDokumen)
                                                                                                                                .addGap(40, 40, 40)
                                                                                                                                .addGroup(jPanelHalAkhirLayout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(jComboBoxPilihDokumen,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                200,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(jLabel1))))
                                                                                                .addGap(0, 37, Short.MAX_VALUE))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanelHalAkhirLayout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGroup(jPanelHalAkhirLayout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                .addGroup(jPanelHalAkhirLayout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                                                                .addComponent(jButtonCartCheckout))
                                                                                                                                .addComponent(jButtonRemove,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                81,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGap(67, 67, 67)
                                                                                                                .addGroup(jPanelHalAkhirLayout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                false)
                                                                                                                                .addComponent(addToCartButton,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(lihatCartButton,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE))
                                                                                                                .addGap(61, 61, 61)))
                                                                .addGap(18, 18, 18)));
                jPanelHalAkhirLayout.setVerticalGroup(
                                jPanelHalAkhirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanelHalAkhirLayout.createSequentialGroup()
                                                                                .addComponent(jLabel1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                76,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(jPanelHalAkhirLayout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jComboBoxPilihDokumen,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jLabelPilihDokumen))
                                                                                .addGap(18, 18, 18)
                                                                                .addGroup(jPanelHalAkhirLayout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jLabelJumlahCopy)
                                                                                                .addComponent(jSpinnerJumlahCopy,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanelHalAkhirLayout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addGroup(jPanelHalAkhirLayout
                                                                                                                .createSequentialGroup()
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(BackButton)
                                                                                                                .addGap(16, 16, 16))
                                                                                                .addGroup(jPanelHalAkhirLayout
                                                                                                                .createSequentialGroup()
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                36,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addGroup(jPanelHalAkhirLayout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                .addComponent(jButtonRemove)
                                                                                                                                .addComponent(addToCartButton))
                                                                                                                .addGap(18, 18, 18)
                                                                                                                .addGroup(jPanelHalAkhirLayout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                .addComponent(jButtonCartCheckout)
                                                                                                                                .addComponent(lihatCartButton))
                                                                                                                .addGap(95, 95, 95)))));

                addToCartButton.getAccessibleContext().setAccessibleName("Lihat Menu");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanelHalAkhir,
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 400,
                                                                Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanelHalAkhir,
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 335,
                                                                Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void addToCartButtonActionPerformed(java.awt.event.ActionEvent evt) throws QuantityException {
                String data = (String) jComboBoxPilihDokumen.getSelectedItem();
                String[] temp = data.split(" ");
                String[] arr = temp[1].split("\\s/\\s");
                temp = null;
                Lembaran l = Data.getMapMenu().get(arr[0]);
                if (l instanceof Buku) {
                        l = (Buku) l;
                }
                int qty = (Integer) jSpinnerJumlahCopy.getValue();
                App.order.addToCart(arr[0], l, qty);
                jComboBoxPilihDokumen.setSelectedItem(null);
                jSpinnerJumlahCopy.setValue(1);
        }// GEN-LAST:event_addToCartButtonActionPerformed

        private void lihatCartButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_lihatCartButtonActionPerformed
                CartCustomer p = new CartCustomer();
                for (Map.Entry<String, Lembaran> entry : App.order.getCart().entrySet()) {
                        String id = entry.getKey();
                        String[] data = new String[4];
                        data[0] = id;
                        data[1] = App.order.getCart().get(id).getMenu();
                        data[2] = String.valueOf(App.order.getCartQty().get(id));
                        data[3] = String.valueOf(App.order.getCart().get(id).getHarga());
                        CartCustomer.getTable().addRow(data);
                }
                p.setVisible(true);
                dispose();
        }// GEN-LAST:event_lihatCartButtonActionPerformed

        private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BackButtonActionPerformed
                App p = new App();
                p.setVisible(true);
                dispose();
        }// GEN-LAST:event_BackButtonActionPerformed

        private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPilihDokumen.setSelectedItem(null);
                RemoveCart p = new RemoveCart();
                p.setVisible(true);
                dispose();
        }// GEN-LAST:event_jButtonRemoveActionPerformed

        private void jButtonCartCheckoutActionPerformed(java.awt.event.ActionEvent evt)
                        throws FileNotFoundException, IOException {// GEN-FIRST:event_jButtonCartCheckoutActionPerformed
                Checkout p = new Checkout();
                for (Map.Entry<String, Lembaran> entry : App.order.getCart().entrySet()) {
                        String id = entry.getKey();
                        String[] data = new String[4];
                        data[0] = id;
                        data[1] = App.order.getCart().get(id).getMenu();
                        data[2] = String.valueOf(App.order.getCartQty().get(id));
                        data[3] = String.valueOf(App.order.getCart().get(id).getHarga());
                        Checkout.getTable().addRow(data);
                }
                p.setVisible(true);
                dispose();
        }// GEN-LAST:event_jButtonCartCheckoutActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(MenuCustomer.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(MenuCustomer.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(MenuCustomer.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(MenuCustomer.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                try {
                                        new MenuCustomer().setVisible(true);
                                } catch (IOException e) {
                                        e.printStackTrace();
                                }
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton BackButton;
        private javax.swing.JButton addToCartButton;
        private javax.swing.JButton jButtonCartCheckout;
        private javax.swing.JButton jButtonRemove;
        private javax.swing.JComboBox<String> jComboBoxPilihDokumen;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabelJumlahCopy;
        private javax.swing.JLabel jLabelPilihDokumen;
        private javax.swing.JPanel jPanelHalAkhir;
        private javax.swing.JSpinner jSpinnerJumlahCopy;
        private javax.swing.JButton lihatCartButton;
        // End of variables declaration//GEN-END:variables
}
